### ISSUE TITLE
Discussion needed on how to best handle non ssl connections

### ISSUE THREAD

**Issue by anoek** [ansible/tower-cli#121]
Currently all connections default to using https. For systems that do not have https setup, a workaround of setting the host to `http://<ip>:<port>/` is possible, but it seems like maybe we should have a config option and/or flag for setting the protocol. Perhaps call it `protocol` with the default value being `https`?

**Comment by AlanCoding** [comment]
Great find. Importantly, the error it gives in these cases in incorrect. Our documentation would seem to indicate that they can specify a host without either the `http://` or `https://` at the start. When it fails to connect, it gives a message about the verify_ssl.

First thing on the agenda should be to make sure we correctly distinguish between connection errors and intentionally failing because of an insecure connection. It should be doing this, but it's not.

**Comment by a31amit** [comment]
Is there any workaround for this problem ? or nightly build where its already patched. ?

**Comment by anoek** [comment]
Current workaround is to specify the `http` protocol in the `host` config, so something like

```
tower-cli config host http://localhost:1234/
```

**Comment by AlanCoding** [comment]
I'm going to put forward a new proposal for this issue:

Let's say that we don't allow a hostname without `http` or `https` if the config variable `verify_ssl` is set to false. We could just raise an error in that case and ask the user to specify it. This would categorically avoid trying to query something that should be http with https.

It also might be one of our few options, since the SSL errors seem so darn difficult to discriminate between.

**Comment by anoek** [comment]
That'd certainly solve it, though I have a pedantic objection being that the terms "host" and "hostname" are misnomers then, so that might get to be confusing for folks.

**Comment by AlanCoding** [comment]
I agree with that sentiment. I would like to get a PR ready in the near-term that will 

1. force the user to provide the protocol whenever verify_ssl is false and 
2. rename some of the terms to avoid confusion
