### ISSUE TITLE
tower-cli crashes on Resource.create with 204 No Content

### ISSUE THREAD

**Issue by hufman** [ansible/tower-cli#193]
I've created some extra Resource subclasses to expose more Tower API endpoints, and that is going well. For example:

```
class TowerGroupHosts(tower_cli.models.Resource):
  endpoint = '/groups/%s/hosts/'
  name = tower_cli.models.Field(unique=True)

  def __init__(self, group_id):
    self.endpoint = TowerGroupHosts.endpoint % (group_id,)
    
# instead of tower_cli.get_resource("host").list()
TowerGroupHosts(group_id).list()
TowerGroupHosts(group_id).get(name="myhostname.something")
```

However, that particular endpoint, when a POST adds a host to it, returns 204 No Content.  `tower_cli.models.base#write` calls `r.json()['id']`, which fails because there is no JSON to parse.

Should the `write` method return None, or should it return a blank OrderedDict((('changed',True),))? Should it detect based on r.status_code==204, or should it have a more explicit API so that the developer acknowledges that the call won't return anything?

**Comment by jangsutsr** [comment]
@hufman Thx for your interest in tower-cli! Looks like you are trying to associate an existing resource with another rather than creating a new resource. Currently we have separated interfaces for these two options. `write` is dedicatedly for creation/modification and that is the cause of the crash you encountered. You can use `_assoc` for association, [please see more of it here.](https://github.com/ansible/tower-cli/blob/master/lib/tower_cli/models/base.py#L755)

**Comment by hufman** [comment]
Yes, Host.associate(group_id) works for this use case. Thank you!
