### ISSUE TITLE
config via environment variable broken

### ISSUE THREAD

**Issue by wenottingham** [ansible/tower-cli#296]
```
[notting@nostromo: ~]$ tower-cli --version
Tower CLI 3.1.3
[notting@nostromo: ~]$ TOWER_HOST=foo.bar TOWER_USERNAME=cow TOWER_PASSWORD=foo TOWER_VERIFY_SSL=false tower-cli config

# Defaults.
username: 
description_on: False
host: 127.0.0.1
verbose: False
certificate: 
format: human
color: True
password: 
verify_ssl: True
```

Have not dug through to see when this last worked as documented.

**Comment by AlanCoding** [comment]
Tried with 3.0.2 and replicated with the steps you gave. The content it echos is unchanged by the env variables. Ping @wwitzel3 so he knows.

**Comment by jangsutsr** [comment]
The problem here is that documentation is not accurate enough. Because environment variables won't be included when using Tower CLI as a command-line tool. Under the hood, env variables only affect `setting.runtime_values` context manager, and that context manager is only used by tests and  ansible tower modules.

Will update docs to remove the confusion.

**Comment by wenottingham** [comment]
Is there any reason *not* to support it when using the CLI?

**Comment by jangsutsr** [comment]
@wenottingham Because reading configuration from env variables has not been taken into consideration before, but we definitely can support it. Ping @AlanCoding for opinion on adding this feature.

**Comment by mauricios** [comment]
This feature is very useful to use Tower CLI in automation tools. I use the environment variables to change Tower CLI configuration programmatically from Hubot scripts, for example changing the user, password and event hostname of Tower CLI depending on the chat user or task request to Hubot from Slack.
