### ISSUE TITLE
Inventory in workflow schema uses unique ID

### ISSUE THREAD

**Issue by jameslabocki** [ansible/tower-cli#302]
The issue I'm running into is that the schema's for workflows use a unique ID for inventories (not for job_templates). This creates a problem, since the ID is unique and created when the inventory is created. So, if you intend to automatically create an inventory and then use it in a workflow, you don't know what the inventory ID is easily.

Here is an example of a schema:

- job_template: aws-infrastructure
  success_nodes:
  - inventory_source: aws (aws-inventory - 59)
    success_nodes:
    - job_template: aws-openshift-install

It would be so much easier if you could refer to an inventory by it's name and not have the " -59" in there.

Here is a bunch of background that led to me realizing the issue: https://github.com/strategicdesignteam/openshift-ansible-contrib/tree/master/reference-architecture/ansible-tower-integration

**Comment by AlanCoding** [comment]
yeah, this is a pretty clear shortcoming of the tool. It's a very reasonable request to do some simple aliasing of the inventory source name.

I'd still like to keep the query as specific as possible. Unfortunately, I think the pk (59 in that case) is specific to the inventory _source_, meaning that there's no way to predict the real name before actually grabbing it. The best I could suggest is to use a querystring that matches `name__startswith=aws (aws-inventory - ` in cases like these.

From the user perspective, I would suggest that we require yaml-file syntax like

```yaml
inventory_source: aws (aws-inventory - x)
```

in order to flag that it should be looked up via this more lenient method.

It would be possible to create a uniqueness problem in the specific case where you created 2 organizations with an inventory & group of the same name. That might be worth a mention in the docs, but nothing more.

**Comment by AlanCoding** [comment]
yeah, this is a pretty clear shortcoming of the tool. It's a very reasonable request to do some simple aliasing of the inventory source name.

I'd still like to keep the query as specific as possible. Unfortunately, I think the pk (59 in that case) is specific to the inventory _source_, meaning that there's no way to predict the real name before actually grabbing it. The best I could suggest is to use a querystring that matches `name__startswith=aws (aws-inventory - ` in cases like these.

From the user perspective, I would suggest that we require yaml-file syntax like

```yaml
inventory_source: aws (aws-inventory - x)
```

in order to flag that it should be looked up via this more lenient method.

It would be possible to create a uniqueness problem in the specific case where you created 2 organizations with an inventory & group of the same name. That might be worth a mention in the docs, but nothing more.

**Comment by AlanCoding** [comment]
There's a change in `master` branch that should now work with the pattern `inventory_source: aws`, where "aws" is the group name. This will break if you have multiple inventories with the same group name in them, but there's not much we can do about that... for now.

**Comment by AlanCoding** [comment]
Discovered a bug with the fix in pre-release testing, will have to keep this open until that is confirmed fix.

**Comment by AlanCoding** [comment]
New use pattern is that

```yaml
inventory_source: aws (aws-inventory -
```

would be acceptable. This grabs the inventory source by "starts with" logic. That strikes me as the most simple solution.

**Comment by AlanCoding** [comment]
This has been tested, mostly in the material now published in the examples folder.
