### ISSUE TITLE
Need help - how can we use list all pages option with python code

### ISSUE THREAD

**Issue by avinash6784** [ansible/tower-cli#369]
I am using tower_cli in python code as like below, we need to get all pages data please help
```
import tower_cli
            from tower_cli import get_resource
            from tower_cli import api
            from tower_cli import conf
            
            with conf.settings.runtime_values(host=host, username=username, password=password):
                c = api.Client()
                response = c.get('inventories')
                inventories =  response.json()
```
Expected output like
`tower-cli  inventory list -a `

Thanks in advance

**Comment by AlanCoding** [comment]
Quick hack at it inside python console:

```python
import tower_cli
res = tower_cli.get_resource('inventory')
res.list(all_pages=True)
```

This gives a dictionary with the API results.

**Comment by avinash6784** [comment]
Thanks @AlanCoding Could you please let me know how can we pass more arguments(multiple arguments) to it. I mean suppose I want filter/search by inventory id/name how can we do it.

**Comment by AlanCoding** [comment]
All filters go through the same ultimate mechanism, which is the `query` parameter, but we have shortcuts to do simple filtering.

```python
>>> res = tower_cli.get_resource('job_template')
>>> res.list(inventory=1)['count']
8
>>> res.list()['count']
9
```

In this usage, you can't put in the inventory name as an alternative. The reason for this is tricky. What you have in this case is the actual `list` method, not the click command. In order to get the full functionality that corresponds to CLI use, there would be some other additional overhead, and that's something that I would like to have.

Alternative, the query parameter can do most of anything you might ever want.

```python
>>> res = tower_cli.get_resource('job_template')
>>> res.list(query=[("inventory__name", "Farmington_animals")])['count']
8
>>> res.list()['count']
9
```

This does the same thing as the prior snippet, it just leverages the Tower query logic to reference by name. The fact that you would have to provide the query as a list of tuples.. that's more than a little non-obvious. But this reflects more of the internal mechanics of the command rather than a good user-facing interface.

You can combine with other parameters, such as `res.list(query=[("inventory__name", "Farmington_animals")], all_pages=True)['results']`, to return all inventories that use that inventory, even if those filled more than 1 page.

**Comment by avinash6784** [comment]
Thanks @AlanCoding 
**tower_cli.get_resource** doesn't supports all Tower API. We need all pages data of 'job_events' and 'activity_streams' API. 
**api.Client()** supports the above 'job_events' and 'activity_streams' API but it returns only one page data, is there any option to get all pages data for 
 c = api.Client()
                response = c.get('inventories')
                inventories =  response.json()

**Comment by AlanCoding** [comment]
I don't have a good answer for you in those cases. We plan to add the activity stream resource. I can't imagine any way for someone to directly interact with job events, but I would support adding that as an abstract resource. Those additions would allow you to interact with these things through the normal `get_resource` mechanism.

**Comment by john-westcott-iv** [comment]
@avinash6784 Try looking in tower_cli/cli/transfer/common.py. In there is a function called load_all_assets which takes a URL and will recurse the next pages in the URL returning everything.

**Comment by AlanCoding** [comment]
Actually I'm going to close this because we did add the activity stream and job events resources.

**Comment by avinash6784** [comment]
Thanks @AlanCoding, will try and let you know.
