### ISSUE TITLE
Bug when passing integers as extra vars 

### ISSUE THREAD

**Issue by tristanbes** [ansible/tower-cli#38]
## Description
tower-cli seems to send integers as string.
If the variable type check is set on integer on the tower side, it makes tower crash.

## Scenario to reproduce the bug:

Under tower, create a job template with a survey
The survey contains only 1 question, 
"which version you want to deploy"
The input has to be an integer.

Then launch a job using `tower-cli`
`tower-cli job launch --job-template 18`

```
Error: The Tower server claims it was sent a bad request.

POST https://tower.yproximite.com/api/v1/job_templates/18/launch/
Params: None
Data: {"extra_vars": "{\n\t\"no_interaction\": true\n}"}

Response: {"variables_needed_to_start": ["'yprox_pr' value missing"]}
```

Which is ok.

Then, we pass extra variable file: 
```yml 
---
yprox_pr: 1553
```

```
tower-cli job launch --job-template 18 --extra-vars extra_vars_1553.yml 

> Error: The Tower server sent back a server error. Please try again later.
```

If I go under tower, and disable the "integer" check (I use "text" instead of "integer). It fixes the issue.

**Comment by AlanCoding** [comment]
This works correctly when I try the same thing. This was tested with Tower version 2.2.2, and ansible version 1.9.2.

Tower Setup
------------------

I set up a job template with a survey that takes a mandatory integer variable (I named the variable i_value). The settings can be viewed from the API endpoint at `/api/v1/job_templates/6/survey_spec/`, where 6 is my specific job template id.

    {
        "spec": [
            {
                "index": 0, 
                "question_name": "Enter an integer", 
                "min": 0, 
                "default": 1, 
                "max": 1000, 
                "question_description": "Please give an integer", 
                "required": true, 
                "variable": "i_value", 
                "choices": "", 
                "type": "integer"
            }
        ], 
        "description": "", 
        "name": ""
    }

This establishes that I have a survey set up that takes a single integer value, and that it is required.

Tower-CLI commands
----------------------

Here are my commands to start a job with the template, giving it a file with the extra parameter, having a value of 15.

    $ touch extra_vars.yml
    $ echo i_value: 15 > extra_vars.yml 
    $ tower-cli job launch --job-template=6 --extra-vars=extra_vars.yml 

This gives the following result, indicating that the job was successful. It received an integer for the integer variable, and it worked.

    == 
    id 
    == 
    11
    == 

I tried it again with "15", as a string, with the following commands:

    $ echo 'i_value: "15"' > extra_vars.yml 
    $ tower-cli job launch --job-template=6 --extra-vars=extra_vars.yml 

This gives the following result, indicating that the job failed. It received a string for the integer variable, and it threw and error.

    Error: The Tower server claims it was sent a bad request.
    
    POST https://{personal URL redacted}
    Params: None
    Data: {"extra_vars": "i_value: \"15\"\n"}
    
    Response: {"variables_needed_to_start": ["'i_value' value 15 is too large (must be no more than1000)", "Value 15 for i_value expected to be an integer"]}

I've also tried switching it around. If I make i_value a text field, then it fails when passing it an integer and passes when passing it a string. This is working as it is should. Maybe it has been fixed since this issue was posted. Can you verify that the bug remains?

**Comment by tristanbes** [comment]
Can't verify, but when I tested it was on 2.0 or 2.1 so I guess I can close this issue based on ur tests
