### ISSUE TITLE
tower-cli readmedocs not rendering correctly

### ISSUE THREAD

**Issue by jlozadad** [ansible/tower-cli#421]
screenshot https://imgur.com/a/GJNgd

**Comment by jangsutsr** [comment]
You got it 👍  That is because we recently merged PR #411 to get up prepared for moving doc site to official ansible docs site, and readthedocs.io cannot link some static files introduced in that PR. Now  you can still reference `/en/v3.2.0/`, which is dedicated for 3.2.0 release and keeps original docs style.

**Comment by AlanCoding** [comment]
working for me now http://tower-cli.readthedocs.io/en/latest/
