### ISSUE TITLE
role list drops --team flag when --all-pages is specified

### ISSUE THREAD

**Issue by kfattig** [ansible/tower-cli#647]
If `--all-pages` and `--team` are specified when calling `role list` in the CLI , `--team` gets lost after the first page of results.  The first page is requested correctly from `/api/v2/teams/X/roles/`, but subsequent pages are fetched from `/api/v2/roles` .

Since 'team' is not a valid attribute for a role, [data_endpoint strips it](https://github.com/ansible/tower-cli/blob/867164ed42a3a28d953cb005b70c601d874f5f20/tower_cli/resources/role.py#L177).  This works for [one-page calls to list](https://github.com/ansible/tower-cli/blob/867164ed42a3a28d953cb005b70c601d874f5f20/tower_cli/resources/role.py#L306) , but [the all_pages loop ](https://github.com/ansible/tower-cli/blob/867164ed42a3a28d953cb005b70c601d874f5f20/tower_cli/models/base.py#L555 ) makes list calls without the `team` field.

Here's a sample, snipped to the first 2 API calls:
```
tower-cli role list --team 8 --all-pages --verbose
*** DETAILS: Getting records. *************************************************
GET https://tower-test/api/v2/teams/8/roles/
Params: []

*** DETAILS: Getting records. *************************************************
GET https://tower-test/api/v2/roles/
Params: [('page', 2)]

```

This returns every role in the system, rather than just those for team 8.

**Comment by AlanCoding** [comment]
Thanks, you've done some good research on this topic. The fact that the endpoint regresses to `/roles/` instead of `/teams/8/roles/` is the point where I would prefer to address the issue myself.

You can see that the first page is implemented differently than the subsequent pages in the base class:

https://github.com/ansible/tower-cli/blob/867164ed42a3a28d953cb005b70c601d874f5f20/tower_cli/models/base.py#L539-L560

The 2nd page and beyond are all recursive calls to `self.list`, which in the case of roles, does some additional unwanted work defined in the subclass.

It certainly seems bad that the Role class `data_endpoint` method is not idempotent, and it could be addressed via that route, which might be how your patch is going about the problem (although I need to digest it further).

However, I would argue that the extremely simple fix that presents itself is to make the `list` method non-recursive, replacing the calls to `list` with calls to `read` instead.

**Comment by kfattig** [comment]
@AlanCoding Re-implemented based on your suggestion:
https://github.com/kfattig/tower-cli/tree/role_list_team_fix_read

**Comment by AlanCoding** [comment]
That looks great! I'll check out your branch and test some time soon. I can merge it on my own if need be, but you might also want to make a new PR to replace your old one.
