### ISSUE TITLE
Add more detail to job `list` and `get` output

### ISSUE THREAD

**Issue by jlaska** [ansible/tower-cli#73]
Currently, the output from `tower-cli job list` and `tower-cli job get` is too terse and only includes an `id`.  Perhaps additional attributes could be added, such as `name`, `inventory`, `launched_by` etc...

This issue is about deciding which fields are relevant to surface, and adding them to the `tower-cli job [list|get]` sub-commands.

**Comment by AlanCoding** [comment]
The process of coding this is handling job and ad hoc commands at the same time. With latest commit, I have the following being printed:

_job_
- id
- job_template
- created
- status
- elapsed 

_ad hoc command_
- id
- created
- status
- elapsed
- inventory
- module_name
- limit

With all of this, the ad hoc command output is already a little bit crowded.

Getting the username is not as simple. It looks you would want to drill down into summary_fields --> created_by --> username. This also applies for almost every resource that tower-cli deals with. It would probably go in a fairly top-level class and could be included in the get request for everything. I'm not sure if that will fit in this scope. I'll return to it after looking into the other new issue about stdout, because some of the details of implementation will be similar.
