### ISSUE TITLE
Include `result_stdout` in job get output

### ISSUE THREAD

**Issue by jlaska** [ansible/tower-cli#74]
Users should be able to view the `result_stdout` from a job (potentially includes project_update, inventory_update, system_job, ad_hoc_command, and job).

The `result_stdout` should be included in the output from the `get` sub-command.  `tower-cli` should handle cases where the `result_stdout` is too large, and use the "Download" API feature.

**Comment by AlanCoding** [comment]
This issue could also get packaged together with returning the creator's username for a get or list output. It could also be packaged with a reverse lookup for get/list so that instead of showing a number for job_template (for example), it could show the name. This could apply to all related fields. These all require adding some custom logic to browse the API response. However, the stdout issue is unique among these because it will involve making another request in specific resource models.

**Comment by AlanCoding** [comment]
Also covered by the standard out streaming `stdout` also stands alone as its own command.
